import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Dashboard from "./@dashboard/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Simple Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  dashboard,
}: Readonly<{
  children: React.ReactNode;
  dashboard: React.ReactNode;
}>) {
  const isAdmin = true;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="px-8 min-h-screen">
          <Header />
          {children}
          {isAdmin && dashboard}
        </div>
        <Footer />
      </body>
    </html>
  );
}
